Test Branch
Aries972/Hello-world pull request #1
Opened 2022-04-19 18:49 UTC by Aries972

Week 1 Day 2 on Microverse program
In this exercise we learned how to present a new branch for reviewing through a pull request as part of a GITHUB flow.
The branch contains linters files for testing HTML/CSS code.

2022-04-19 23:24 UTC, AnselemOdims requested changes
### Hi @Aries972 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [x] Please kindly ensure that your pull request summary is well descriptive. It should discuss in brief the introduced changes for that branch
- [x] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-19 23:24 UTC, AnselemOdims commented on .gitignore
> +#A gitignore file specifies intentionally untracked files that Git should ignore.
- [ ] Please kindly ensure that `node_modules` is included in the `.gitignore` file. This will ensure that unnecessary files and dependencies are not pushed to remote.

2022-04-20 00:49 UTC, OLIPLICHE approved these changes
Hi @Aries972 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 01:01 UTC, merged

2022-04-20 01:04 UTC, Aries972 commented
Thank you very much for your kind help. 
I completed the merge operation.